# Generated by Django 4.0.4 on 2022-04-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_create_table_led_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='led',
            name='color',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=200, verbose_name='ColorScheme'),
        ),
    ]
