# Generated by Django 4.0.4 on 2022-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_led_color_alter_table_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('fnc_string', models.TextField(default=None, null=True)),
                ('applied_in', models.ManyToManyField(related_name='color_filters', to='table.table')),
            ],
        ),
    ]
