# Generated by Django 4.0.4 on 2022-05-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_colorfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorfilter',
            name='applied_in',
            field=models.ManyToManyField(blank=True, related_name='color_filters', to='table.table'),
        ),
    ]
