# Generated by Django 4.0.4 on 2022-05-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_alter_colorfilter_applied_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_fnc', models.TextField(blank=True, default=None, null=True)),
                ('raw_matrix', models.JSONField(blank=True, default=None, null=True)),
                ('table', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='table.table')),
            ],
        ),
        migrations.CreateModel(
            name='FrameOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_frame', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_after', to='table.animationframe')),
                ('previous_frame', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_before', to='table.animationframe')),
                ('this_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='table.animationframe')),
            ],
        ),
    ]
